Repository bridge2ai/b2ai-standards-registry, pull requests merged in 2025-03, with the labels that each got.

#212 feat: replace PLACEHOLDER with prev entity ID + 1
  .github/scripts/process_issue.py
Labels: enhancement

#214 fix: populate related_to values in process issue script
  .github/ISSUE_TEMPLATE/newEntity.yml
  .github/scripts/process_issue.py
Labels: bug

#230 fix: add missing column for DataStandardOrTool
  scripts/README.md
  scripts/modify_synapse_schema.py
Labels: bug

#243 docs: update author list in 'pyproject.toml'
  pyproject.toml
Labels: documentation
